# DDP
gpus: "1,2,3"
flag: "train"

# Log
log_dir: "./log/crossdataset_image_new/crossdataset_fatformer_vitb16_train"

# Task
if_predict_label: true
if_predict_mask: false

# Model
model:
  name: FatFormer
  init_config:
    backbone: ViT-B/16
    d_model: 768


# Train dataset
train_dataset:
  name: CrossDataset
  dataset_name: CrossDataset
  init_config:
    dataset_config:
      - name: IMDLCrossDataset
        pic_nums: 12641
        init_config:
          image_size: 224
          path: /mnt/data0/public_datasets/IML/CASIAv2_with_label.json
      - name: AIGCCrossDataset
        pic_nums: 12641
        init_config:
          image_size: 224
          path:
            - /mnt/data3/public_datasets/AIGC/GenImage/ADM_train.json
            - /mnt/data3/public_datasets/AIGC/GenImage/BigGAN_train.json
            - /mnt/data3/public_datasets/AIGC/GenImage/glide_train.json
            - /mnt/data3/public_datasets/AIGC/GenImage/Midjourney_train.json
            - /mnt/data3/public_datasets/AIGC/GenImage/stable_diffusion_v_1_4_train.json
            - /mnt/data3/public_datasets/AIGC/GenImage/stable_diffusion_v_1_5_train.json
            - /mnt/data3/public_datasets/AIGC/GenImage/VQDM_train.json
            - /mnt/data3/public_datasets/AIGC/GenImage/wukong_train.json
      - name: DocumentCrossDataset
        pic_nums: 12641
        init_config:
          image_size: 224
          path:
            - /mnt/data1/public_datasets/Doc/cutted_datasets_alls/OSTF_train
            - /mnt/data1/public_datasets/Doc/cutted_datasets_alls/RealTextManipulation_train
            - /mnt/data1/public_datasets/Doc/cutted_datasets_alls/T-SROIE_train
            - /mnt/data1/public_datasets/Doc/cutted_datasets_alls/Tampered-IC13_train
      - name: DeepfakeCrossDataset
        pic_nums: 12641
        init_config:
          image_size: 224
          path: /mnt/data1/public_datasets/Deepfake
          config_file: /mnt/data1/public_datasets/Deepfake/FaceForensics++.json

#  Test dataset (one or many)
test_dataset:
  - name: JsonDataset
    dataset_name: IMD2020
    init_config:
      image_size: 224
      path: /mnt/data0/public_datasets/IML/IMD_20_1024_full.json
      # Dataset specific setting
      is_resizing: true
      is_padding: false
  - name: AIGCLabelDataset
    dataset_name: DiffusionForensics_test
    init_config:
      image_size: 224
      path: /mnt/data3/public_datasets/AIGC/DiffusionForensics/images/test.json
  - name: DocumentCrossDataset
    dataset_name: OSTF_test
    init_config:
      image_size: 224
      path:
        - /mnt/data1/public_datasets/Doc/cutted_datasets_alls/OSTF_test
  - name: DeepfakeCrossDataset
    dataset_name: FF-DF_test
    init_config:
      image_size: 224
      path: /mnt/data1/public_datasets/Deepfake
      config_file: /mnt/data1/public_datasets/Deepfake/FF-DF.json
      split_mode: test

# Transform
transform:
  name: AIGCTransform
  init_config:
    norm_type: clip


# Evaluators
evaluator:
  - name: ImageF1
    init_config:
      threshold: 0.5

# Training related
batch_size: 256
test_batch_size: 64
epochs: 20
accum_iter: 1
record_epoch: 15  # Save the best only after record epoch.

# Test related
no_model_eval: false
test_period: 1

# Logging & TensorBoard
log_per_epoch_count: 20

# DDP & AMP settings
find_unused_parameters: true
use_amp: true

# Optimizer parameters
weight_decay: 0.05
lr: 2e-5
blr: 0.001
min_lr: 2e-6
warmup_epochs: 1

# Device and training control
device: "cuda"
seed: 42
resume: ""
start_epoch: 0
num_workers: 8
pin_mem: true

# Distributed training parameters
world_size: 1
local_rank: -1
dist_on_itp: false
dist_url: "env://"

